// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_SscOI3z64_TbTiJ2VSSIB_VB0TsdDI',
    appId: '1:371966886791:web:a8bc1483ca19ac80778922',
    messagingSenderId: '371966886791',
    projectId: 'kayal-51e79',
    authDomain: 'kayal-51e79.firebaseapp.com',
    storageBucket: 'kayal-51e79.appspot.com',
    measurementId: 'G-VF547Z52MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9PD_4D4TSOF-f1zacZbF-rx3d-M7UNi0',
    appId: '1:371966886791:android:de78ccb21c688973778922',
    messagingSenderId: '371966886791',
    projectId: 'kayal-51e79',
    storageBucket: 'kayal-51e79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQcazSb3_RjkkhC8h0OCduHsfBSPlfMx4',
    appId: '1:371966886791:ios:38801b54f2ce0d81778922',
    messagingSenderId: '371966886791',
    projectId: 'kayal-51e79',
    storageBucket: 'kayal-51e79.appspot.com',
    androidClientId: '371966886791-kgfs6udr8bt2k8volr38ofe65l7hgdmu.apps.googleusercontent.com',
    iosClientId: '371966886791-5c2pvt5fba5tt46ifdf8r4clp67n816i.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.eFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQcazSb3_RjkkhC8h0OCduHsfBSPlfMx4',
    appId: '1:371966886791:ios:387f8655ab12b6ff778922',
    messagingSenderId: '371966886791',
    projectId: 'kayal-51e79',
    storageBucket: 'kayal-51e79.appspot.com',
    androidClientId: '371966886791-kgfs6udr8bt2k8volr38ofe65l7hgdmu.apps.googleusercontent.com',
    iosClientId: '371966886791-8dvdf78snasvv36a8e52v2rfv5pi5ifb.apps.googleusercontent.com',
    iosBundleId: 'com.haqtoapp.organization.flutterGrocery.RunnerTests',
  );
}
